### PR TITLE
update all the dependencies!

### PR DESCRIPTION
**Pull request by sorahn**
OK here we go.
* updated all the dependencies.
* koa and koa-router to be peer dependencies
* fix all the tests so they use `ctx`

### CODE REVIEW

**Comment by sorahn** [comment]
Fixes #1 

I'm not sure how to tell Travis to stop testing node v4.

**Comment by dominicbarnes** [comment]
Thank you very much! I'll take a look tonight, and we don't have to worry about node v4 so I'll fix that.

**Comment by sorahn** [comment]
@dominicbarnes any update on this?

**Comment by dominicbarnes** [comment]
I'm gonna merge this and make a few alterations. (updating travis, switching to standard instead of an eslint+config, etc)

Thanks for the contribution! I'll ping here again once I've released a new version.

**Comment by sorahn** [comment]
Awesome.  Great news!

If you're going to go ahead and switch to something like standard I'd recommend making the jump straight to [Prettier](https://prettier.io/).  The editor support or git-hook stuff for it is pretty awesome at making all the code look exactly the same.

I could make a PR with a recommended setup for that if you're interested.

**Comment by dominicbarnes** [comment]
@sorahn thanks, but I'm already familiar with standard and the tooling, so I'll stick with that.

**Comment by dominicbarnes** [comment]
Just tagged v1.0.0 with koa2 support!

**Pull request merged**
